#versione docker compose
version: '3.9'

services:
  app:
    build:
      context: .
    container_name: django_container
    ports:
      - "8000:8000"
    command:
      sh -c " python manage.py runserver 0.0.0.0:8000"
